//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI.Controls
{


    public partial class SurveyDisplay
    {

        protected global::System.Web.UI.WebControls.Panel pnlSurveyContainer;

        protected global::System.Web.UI.WebControls.Literal litSurveyTitle;

        protected global::System.Web.UI.WebControls.Panel pnlSurveyContent;

        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        protected global::System.Web.UI.WebControls.Button btnSubmitSurvey;

        protected global::System.Web.UI.WebControls.Button btnSkipSurvey;

        protected global::System.Web.UI.WebControls.Panel pnlSurveyMessage;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertSurveyMessage;

        protected global::System.Web.UI.WebControls.Label lblSurveyMessage;
    }
}
