//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI
{


    public partial class AdminBilling
    {

        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// lblAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAlert;

        /// <summary>
        /// btnOpenCreateModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnOpenCreateModal;

        /// <summary>
        /// ddlFilterType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterType;

        /// <summary>
        /// ddlFilterStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

        /// <summary>
        /// txtFilterUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterUser;

        /// <summary>
        /// txtFilterDocumentNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterDocumentNumber;

        /// <summary>
        /// txtFilterFromDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterFromDate;

        /// <summary>
        /// txtFilterToDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilterToDate;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// litBillingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBillingCount;

        /// <summary>
        /// gvBilling control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBilling;

        /// <summary>
        /// hfOpenCreateModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfOpenCreateModal;

        /// <summary>
        /// hfOpenViewModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfOpenViewModal;

        /// <summary>
        /// vsCreateDocument control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsCreateDocument;

        /// <summary>
        /// lblCreateError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCreateError;

        /// <summary>
        /// ddlDocumentType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDocumentType;

        /// <summary>
        /// rfvDocumentType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDocumentType;

        /// <summary>
        /// ddlDocumentUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDocumentUser;

        /// <summary>
        /// rfvDocumentUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDocumentUser;

        /// <summary>
        /// txtDocumentNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDocumentNumber;

        /// <summary>
        /// txtIssueDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIssueDate;

        /// <summary>
        /// txtDueDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;

        /// <summary>
        /// txtNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        /// <summary>
        /// ddlItemProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlItemProduct;

        /// <summary>
        /// txtItemDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtItemDescription;

        /// <summary>
        /// txtItemQuantity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtItemQuantity;

        /// <summary>
        /// txtItemTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtItemTax;

        /// <summary>
        /// btnAddItem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddItem;

        /// <summary>
        /// rptItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptItems;

        /// <summary>
        /// litSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubtotal;

        /// <summary>
        /// litTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTax;

        /// <summary>
        /// litTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>
        /// btnCreateDocument control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateDocument;

        /// <summary>
        /// litViewTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litViewTitle;

        /// <summary>
        /// litViewHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litViewHeader;

        /// <summary>
        /// rptViewItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptViewItems;

        /// <summary>
        /// litViewSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litViewSubtotal;

        /// <summary>
        /// litViewTax control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litViewTax;

        /// <summary>
        /// litViewTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litViewTotal;
    }
}
