//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI
{


    public partial class AdminRoles
    {

        /// <summary>
        /// upRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upRoles;

        /// <summary>
        /// hdnSelectedRoleId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedRoleId;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// btnNewRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnNewRole;

        /// <summary>
        /// rptRoles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRoles;

        /// <summary>
        /// pnlNoRoles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoRoles;

        /// <summary>
        /// pnlRoleDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRoleDetail;

        /// <summary>
        /// litRoleHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRoleHeader;

        /// <summary>
        /// badgeRoleStatus control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeRoleStatus;

        /// <summary>
        /// vsRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsRole;

        /// <summary>
        /// txtRoleName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRoleName;

        /// <summary>
        /// rfvRoleName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRoleName;

        /// <summary>
        /// txtRoleDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRoleDescription;

        /// <summary>
        /// chkIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        /// <summary>
        /// cblPermissions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBoxList cblPermissions;

        /// <summary>
        /// txtAssignUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAssignUsername;

        /// <summary>
        /// btnAssignRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAssignRole;

        /// <summary>
        /// rptAssignedUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAssignedUsers;

        /// <summary>
        /// pnlNoAssignedUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAssignedUsers;

        /// <summary>
        /// btnDeleteRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnDeleteRole;

        /// <summary>
        /// btnSaveRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnSaveRole;
    }
}
