//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI
{


    public partial class AdminSurveys
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ucLanguageSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UI.Controls.LanguageSelector ucLanguageSelector;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.ScriptManager smAdminSurveys;

        protected global::System.Web.UI.WebControls.HiddenField hfSelectedSurveyId;

        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.Label lblAlert;

        protected global::System.Web.UI.WebControls.Literal litAlertClose;

        protected global::System.Web.UI.WebControls.Button btnRefreshSurveys;

        protected global::System.Web.UI.WebControls.Button btnNewSurvey;

        protected global::System.Web.UI.WebControls.GridView gvSurveys;

        protected global::System.Web.UI.WebControls.Panel pnlSurveyEditor;

        protected global::System.Web.UI.WebControls.Literal litEditorTitle;

        protected global::System.Web.UI.WebControls.Button btnCloseEditor;

        protected global::System.Web.UI.WebControls.TextBox txtSurveyTitle;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSurveyTitle;

        protected global::System.Web.UI.WebControls.DropDownList ddlSurveyLanguage;

        protected global::System.Web.UI.WebControls.TextBox txtSurveyDescription;

        protected global::System.Web.UI.WebControls.TextBox txtSurveyStart;

        protected global::System.Web.UI.WebControls.TextBox txtSurveyEnd;

        protected global::System.Web.UI.WebControls.CheckBox chkSurveyIsActive;

        protected global::System.Web.UI.WebControls.Label lblSurveyIsActive;

        protected global::System.Web.UI.WebControls.CheckBox chkAllowMultipleResponses;

        protected global::System.Web.UI.WebControls.Label lblAllowMultipleResponses;

        protected global::System.Web.UI.WebControls.Button btnSaveSurvey;

        protected global::System.Web.UI.WebControls.Button btnCancelSurvey;

        protected global::System.Web.UI.WebControls.Panel pnlQuestionSection;

        protected global::System.Web.UI.WebControls.Button btnAddQuestion;

        protected global::System.Web.UI.WebControls.GridView gvQuestions;

        protected global::System.Web.UI.WebControls.Panel pnlQuestionEditor;

        protected global::System.Web.UI.WebControls.TextBox txtQuestionText;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuestionText;

        protected global::System.Web.UI.WebControls.DropDownList ddlQuestionType;

        protected global::System.Web.UI.WebControls.TextBox txtQuestionOrder;

        protected global::System.Web.UI.WebControls.CheckBox chkQuestionRequired;

        protected global::System.Web.UI.WebControls.Label lblQuestionRequired;

        protected global::System.Web.UI.WebControls.Button btnSaveQuestion;

        protected global::System.Web.UI.WebControls.Button btnCancelQuestion;

        protected global::System.Web.UI.WebControls.Panel pnlOptionEditor;

        protected global::System.Web.UI.WebControls.GridView gvOptions;

        protected global::System.Web.UI.WebControls.TextBox txtOptionText;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptionText;

        protected global::System.Web.UI.WebControls.TextBox txtOptionValue;

        protected global::System.Web.UI.WebControls.TextBox txtOptionOrder;

        protected global::System.Web.UI.WebControls.Button btnSaveOption;

        protected global::System.Web.UI.WebControls.Button btnCancelOption;
    }
}



