//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI
{


    public partial class News
    {

        /// <summary>
        /// pnlPublicAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPublicAlert;

        /// <summary>
        /// lblPublicAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPublicAlert;

        /// <summary>
        /// txtPublicSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPublicSearch;

        /// <summary>
        /// ddlPublicLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPublicLanguage;

        /// <summary>
        /// btnSearchNews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearchNews;

        /// <summary>
        /// btnResetNewsSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnResetNewsSearch;

        /// <summary>
        /// litNewsResultsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNewsResultsCount;

        /// <summary>
        /// rptNews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptNews;

        /// <summary>
        /// pnlNoNews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoNews;

        /// <summary>
        /// txtSubscribeEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSubscribeEmail;

        /// <summary>
        /// ddlSubscribeLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSubscribeLanguage;

        /// <summary>
        /// btnSubscribeNewsletter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubscribeNewsletter;

        /// <summary>
        /// lblSubscribeFeedback control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubscribeFeedback;

        /// <summary>
        /// litArticleModalTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litArticleModalTitle;

        /// <summary>
        /// litArticleModalDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litArticleModalDate;

        /// <summary>
        /// litArticleModalLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litArticleModalLanguage;

        /// <summary>
        /// litArticleModalViews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litArticleModalViews;

        /// <summary>
        /// litArticleModalContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litArticleModalContent;
    }
}
