//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirebot_TFI
{


    public partial class Subscriptions
    {

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;

        protected global::System.Web.UI.WebControls.DropDownList ddlProducts;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvProduct;

        protected global::System.Web.UI.WebControls.TextBox txtCardholderName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCardholder;

        protected global::System.Web.UI.WebControls.TextBox txtCardNumber;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCardNumber;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCardNumber;

        protected global::System.Web.UI.WebControls.DropDownList ddlExpirationMonth;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvExpirationMonth;

        protected global::System.Web.UI.WebControls.DropDownList ddlExpirationYear;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvExpirationYear;

        protected global::System.Web.UI.WebControls.Button btnSubscribe;

        protected global::System.Web.UI.WebControls.Panel pnlNoSubscriptions;

        protected global::System.Web.UI.WebControls.Repeater rptSubscriptions;
    }
}
